# Generated by Django 2.0.6 on 2018-06-18 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0011_auto_20180606_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='webhook_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='webhook_last_updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
